services:
  traefik:
    image: traefik:v3.2
    restart: unless-stopped
    depends_on:
      - webapp
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.certresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.certresolver.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.certresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - 80:80
      - 443:443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  webapp:
    restart: unless-stopped
    deploy:
      replicas: 2
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.webapp.loadbalancer.server.port=8080"
      - "traefik.http.routers.webapp.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.webapp.entrypoints=websecure"
      - "traefik.http.routers.webapp.tls.certresolver=certresolver"

volumes:
  letsencrypt:
