services:
  traefik:
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports: !override
      - 5000:80
      - 8080:8080

  webapp:
    build:
      context: ./api
      dockerfile: Dockerfile
    labels: !override
      - "traefik.enable=true"
      - "traefik.http.services.webapp.loadbalancer.server.port=8080"
      - "traefik.http.routers.webapp.rule=Host(`localhost`)"
      - "traefik.http.routers.webapp.entrypoints=web"
